version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/London"
    assignees:
      - "willfantom"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore: "
